modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="salty_naruto"
version="1.0.0"
displayName="Salty's Naruto"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="SaltyFrappuccino, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.salty_naruto]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.salty_naruto]]
    modId="kleidersplayerrenderer"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.salty_naruto]]
    modId="damage-indicator-reborn"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration